### ISSUE TITLE
AssertionError in PostTreatment - gromacs run

### ISSUE THREAD

**Issue by gokulalgates** [fhh2626/BFEE2#88]
While working on Post Treatment, Getting the following error 

AssertionError
Traceback (most recent call last):
  File "/home/singam2/anaconda3.7/envs/bfee/lib/python3.9/site-packages/BFEE2/gui.py", line 1369, in f
    self._showGeometricResults(unit)
  File "/home/singam2/anaconda3.7/envs/bfee/lib/python3.9/site-packages/BFEE2/gui.py", line 1250, in _showGeometricResults
    result = pTreat.geometricBindingFreeEnergy(pmfs, parameters)
  File "/home/singam2/anaconda3.7/envs/bfee/lib/python3.9/site-packages/BFEE2/postTreatment.py", line 229, in geometricBindingFreeEnergy
    contributions[6] = self._geometricCalculateSI(
  File "/home/singam2/anaconda3.7/envs/bfee/lib/python3.9/site-packages/BFEE2/postTreatment.py", line 164, in _geometricCalculateSI
    assert(rStar <= pmf[0][-1])
AssertionError

what would be the reason for this?

**Comment by fhh2626** [comment]
hi @gokulalgates ,

You need to set a reasonable r* based on your PMF of step 7.

I will let BFEE2 raise a more readable error message in the next release.

Good luck,
Haohao
